name: Github Actions runner
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build
  SSh-into-power:
      runs-on: self-hosted
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: ssh into the power machine
        run: |
          echo -e "Display the bastion machine architecture\n" 
          arch
          rm -rf /root/power-runner-ssh
          git clone https://github.com/mayurwaghmode/power-runner-ssh.git /root/power-runner-ssh
          sshpass -p ${{ secrets.PASSWORD }} ssh root@${{ secrets.POWER_MACHINE_IP }} < /root/power-runner-ssh/script-to-run-on-power.sh
