name: Github Actions runner on ppc64le
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ multi-arch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build
  workflow-on-self-hosted-runner:
      runs-on: self-hosted
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build multi-arch images on self hosted runner(x86)
        run: |
          echo -e "Display the self hosted runner architecture\n" 
          arch
          buildah bud --platform=linux/amd64 -t quay.io/mayurwaghmode111/gha-multi-arch:amd64
          buildah bud --platform=linux/ppc64le -t quay.io/mayurwaghmode111/gha-multi-arch:ppc64le
          buildah manifest create quay.io/mayurwaghmode111/gha-multi-arch
          buildah manifest add quay.io/mayurwaghmode111/gha-multi-arch quay.io/mayurwaghmode111/gha-multi-arch:amd64
          buildah manifest add quay.io/mayurwaghmode111/gha-multi-arch quay.io/mayurwaghmode111/gha-multi-arch:ppc64le
          buildah login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_PWD }} quay.io
          podman manifest push --all quay.io/mayurwaghmode111/gha-multi-arch quay.io/mayurwaghmode111/gha-multi-arch:multi-arch
          buildah manifest rm quay.io/mayurwaghmode111/gha-multi-arch
      - name: Fix ssh Could not resolve hostname
        run: |
          ssh-keyscan ${{ secrets.PPC64LE_MACHINE_IP }}  >> ~/.ssh/known_hosts # Add live server IP to known hosts.   
      - name: ssh into the ppc64le machine and build the docker image natively
        run: |
          echo -e "Display the bastion machine architecture\n" 
          arch
          rm -rf /root/power-runner-ssh
          git clone -b multi-arch https://github.com/mayurwaghmode/power-runner-ssh.git /root/power-runner-ssh
          echo -e "SSH into the Power machine and execute the script\n"
          ssh root@${{ secrets.PPC64LE_MACHINE_IP }} < /root/power-runner-ssh/script-to-run-on-ppc64le.sh
